-- 019_fix_status_checks_and_indexes.sql
-- This migration previously rebuilt the seamless/screen/welded pipe tables to
-- widen their status CHECK constraints and added pipe traceability indexes.
-- Those tables are REMOVED in the SQLite + generic-ERP rewrite (see 002/003/018),
-- so the rebuilds are obsolete.
--
-- The generic equivalents of the traceability indexes (on item_id instead of
-- (pipe_type, pipe_id)) were folded directly into 005_create_inventory.sql.
-- This migration intentionally contains no statements.
